### ISSUE TITLE
Error running CovEST

### ISSUE THREAD

**Issue by capoony** [mhozza/covest#15]
Hello, 

when running CovEST, I get the following error, which I guess has something to do with an updated version of SciPy

```
covest
Invalid MIT-MAGIC-COOKIE-1 keyTraceback (most recent call last):
  File "/opt/venv/covest/bin/covest", line 33, in <module>
    sys.exit(load_entry_point('covest==0.5.6', 'console_scripts', 'covest')())
  File "/opt/venv/covest/bin/covest", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/venv/covest/lib/python3.8/site-packages/covest/covest.py", line 10, in <module>
    from .data import load_histogram, parse_data, print_output, save_histogram
  File "/opt/venv/covest/lib/python3.8/site-packages/covest/data.py", line 10, in <module>
    from .models import BasicModel, models, select_model
  File "/opt/venv/covest/lib/python3.8/site-packages/covest/models.py", line 10, in <module>
    from scipy.misc import comb
ImportError: cannot import name 'comb' from 'scipy.misc' (/opt/venv/covest/lib/python3.8/site-packages/scipy/misc/__init__.py)
```

Thanks a lot for your help

**Comment by zpcohen** [comment]
same error.

**Comment by mvolar** [comment]
go into the models.py file and change the line

```
from scipy.misc import comb
```

into:

```
from scipy.special import comb
```

**Comment by simleopold** [comment]
I have the same problem and I cannot change the line.
